name: Linters

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.5"
      - name: flake8
        uses: py-actions/flake8@v2
      - name: black
        uses: jpetrucciani/black-check@master
        with:
          path: '.'
